domain = "example.com"
debug = false
secret = "SQ3tEErWMv" # What shouldn't be committed will be done


[database]
    host = "localhost"
	port = 3306
	user = "root"
	password = ""
	name = "dbplanner"

