version: '2'

services:
  valhalla:
    image: lkwg82/h2o-http2-server
    ports:
     - "80:80"
     - "443:443"
    volumes:
       - "/etc/h2o:/etc/h2o"
       - "/etc/letsencrypt:/etc/letsencrypt"
       - "/var/log/h2o:/var/log/h2o"
    working_dir: /etc/h2o
    restart: always